<% app_name = Rails.application.class.parent.to_s.underscore %>

default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password:
  encoding: unicode
  database: <%= app_name + '_' + Rails.env %>
  pool:     5
  timeout:  5000

development:
  <<: *default

# Warning: The database defined as "test" will be erased and re-generated when you run "rake".
# Do not set this db to the same as development or production.
test: &test
  <<: *default
  database: <%= app_name + '_test' %>

cucumber:
  <<: *test
